import Perfil from "../components/loja/perfil"
import Categorias from "../components/loja/categorias"

export default function Home() {
  return (
    <div>
      <head>
        <title>SoftMenu</title>
        <meta name="description" content="Generated by create next app" />
      </head>

      <main>
        <header>
          <Perfil/>
        </header>

        <Categorias/>
      </main>
    </div>
  )
}
