export default function Home() {
  return (
    <div>
      <head>
        <title>SoftMenu</title>
        <meta name="description" content="Generated by create next app" />
      </head>
    </div>
  )
}
